server:
  port: 8080
  servlet:
    path: /

mybatis-plus:
  typeAliasesPackage: sk.springboot.entity
  mapper-locations: classpath:sk/springboot/mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_empty
      column-underline: false
      #capital-mode: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      refresh: true
      #meta-object-handler: com.baomidou.springboot.xxx
      #sql-injector: com.baomidou.springboot.xxx
      #sql-injector: com.baomidou.springboot.xxx

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

thymeleaf:
  encoding: UTF-8
  cache: false
  prefix: classpath:templates/
  suffix: .html

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql